exports.PROPERTY_TYPE_TENT = "PROPERTY_TYPE_TENT";
exports.PROPERTY_TYPE_GLAMPING = "PROPERTY_TYPE_GLAMPING";
exports.PROPERTY_TYPE_RVCAR = "RVCAR";
exports.PROPERTY_TYPE_HOMESTAY = "HOMESTAY";

exports.IMAGE = "IMAGE";
exports.COVER = "COVER";

exports.PHONE = "PHONE";
exports.FACEBOOK = "FACEBOOK";
exports.LINE = "LINE";
exports.INSTAGRAM = "INSTAGRAM";
exports.TWITTER = "TWITTER";
exports.WEBSITE = "WEBSITE";
exports.ETC = "ETC";

exports.PROPERTY = "PROPERTY";
exports.GENERAL = "GENERAL";
exports.SERVICE = "SERVICE";
exports.ACTIVITY = "ACTIVITY";
exports.RULE = "RULE";

exports.RESET_PASSWORD = "RESET_PASSWORD";
exports.VERIFY_SIGNUP = "VERIFY_SIGNUP";
